In [6]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [7]:
from src.data_cleaning import clean_data

In [12]:
clean_data(
    "D:/Skill Graph/Data/Raw/DataAnalyst.csv",
    "D:/Skill Graph/data/processed/cleaned_jobs.csv",
)

In [13]:
import pandas as pd

df = pd.read_csv("D:/Skill Graph/data/processed/cleaned_jobs.csv")

df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD)
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD)
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD)
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2252 entries, 0 to 2251
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          2252 non-null   object
 1   Salary Estimate    2252 non-null   object
 2   Job Description    2252 non-null   object
 3   Rating             2252 non-null   float64
 4   Company Name       2252 non-null   object
 5   Location           2252 non-null   object
 6   Headquarters       2252 non-null   object
 7   Size               2252 non-null   object
 8   Founded            2252 non-null   int64
 9   Type of ownership  2252 non-null   object
 10  Industry           2252 non-null   object
 11  Sector             2252 non-null   object
 12  Revenue            2252 non-null   object
dtypes: float64(1), int64(1), object(11)
memory usage: 228.8+ KB

In [15]:
df.isnull().sum()

Job Title            0
Salary Estimate      0
Job Description      0
Rating               0
Company Name         0
Location             0
Headquarters         0
Size                 0
Founded              0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
dtype: int64

In [16]:
df.describe()

            Rating      Founded
count  2252.000000  2252.000000
mean      3.162478  1399.144316
std       1.663286   901.646960
min      -1.000000    -1.000000
25%       3.100000    -1.000000
50%       3.600000  1979.000000
75%       4.000000  2002.000000
max       5.000000  2019.000000